---

# resize var partition but dont fail on this
- name: resize var for docker
  lvol:
    vg: "{{docker_var_vg}}"
    lv: "{{docker_var_lv}}"
    size: "{{docker_var_size}}"
    shrink: no
  register: lv_resize
  ignore_errors: True

- name: resize fs for docker
  command: "xfs_growfs /dev/{{docker_var_vg}}/{{docker_var_lv}}"
  when: lv_resize | success