---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
# common tasks that most if not all machines should have

# most machines will need selinux python for ansible
- name: Install selinux python bindings
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

# set selinux policy right off the bat.
- name: Set SELinux Policy
  selinux: 
    state: "{{ selinux.state }}" 
    policy: "{{ selinux.policy }}"