---
# tasks file for /etc/ansible/roles/yum-updates

- name: Install yum-cron package
  yum:
    name: yum-cron
    state: present

- name: change yum-cron config to update for security
  copy:
    src: yum-cron.conf
    dest: /etc/yum/yum-cron.conf
    mode: 0644  
  notify: restart_yumcron

- name: enable and start service
  service:
    name: yum-cron
    enabled: yes
    state: started

